apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pv-pvc.yaml

namespace: stackweaver

helmCharts:
  - name: stackweaver
    repo: oci://ghcr.io/vhco-pro/charts
    version: 0.11.0
    releaseName: stackweaver
    namespace: stackweaver
    valuesFile: values.yaml
